"""Exports a source workflow as a committed, deployable Databricks Asset Bundle.

Ties the whole pipeline together for the git -> DAB -> Databricks flow:
parse the workflow, generate its spec (offline rule-based here; the app's
LLM path produces the same PipelineSpec shape), render the chosen artifact
format, and write a self-contained bundle directory:

    <out>/
      databricks.yml      one target, generated by deploy/dab.py
      src/<name>.py       the rendered job script / notebook / SDP module

The output is meant to be committed to git and deployed with
`databricks bundle deploy` (auth via DATABRICKS_HOST / DATABRICKS_TOKEN env
vars — never stored in the bundle).

Usage:
    python -m deploy.export --workflow tests/fixtures/alteryx/sales_summary.yxmd \
        --format notebook --out bundles/sales_summary \
        --host https://<workspace>.cloud.databricks.com \
        --catalog workspace --schema default
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import cast

from app.offline_convert import naive_spec_from_workflow
from convert.renderer import render_databricks_notebook, render_pyspark, render_sdp
from convert.spec import TargetRef
from deploy.dab import ArtifactFormat, single_target_bundle, write_databricks_yml
from ingest.alteryx.parser import parse_yxmd

_RENDERERS = {
    "job": render_pyspark,
    "notebook": render_databricks_notebook,
    "sdp": render_sdp,
}


def export_bundle(
    workflow_path: str | Path,
    output_dir: str | Path,
    workspace_host: str,
    artifact_format: ArtifactFormat = "notebook",
    catalog: str = "workspace",
    schema: str = "default",
    bundle_name: str = "migration-accelerator",
) -> Path:
    """Parse, convert, render, and write a deployable bundle directory."""
    workflow = parse_yxmd(workflow_path)
    target = TargetRef(catalog=catalog, schema=schema, layer="bronze")
    spec = naive_spec_from_workflow(workflow, target)
    code = _RENDERERS[artifact_format](spec)

    out = Path(output_dir)
    src_dir = out / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    (src_dir / f"{spec.name}.py").write_text(code, encoding="utf-8")

    bundle = single_target_bundle(
        bundle_name=bundle_name,
        pipeline_name=spec.name,
        python_file=f"./src/{spec.name}.py",
        workspace_host=workspace_host,
        catalog=catalog,
        schema=schema,
        artifact_format=artifact_format,
    )
    write_databricks_yml(bundle, out / "databricks.yml")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workflow", required=True, help="Path to the source .yxmd file")
    parser.add_argument("--out", required=True, help="Bundle output directory")
    parser.add_argument("--host", required=True, help="Databricks workspace URL")
    parser.add_argument("--format", default="notebook", choices=sorted(_RENDERERS))
    parser.add_argument("--catalog", default="workspace")
    parser.add_argument("--schema", default="default")
    parser.add_argument("--bundle-name", default="migration-accelerator")
    args = parser.parse_args()

    out = export_bundle(
        workflow_path=args.workflow,
        output_dir=args.out,
        workspace_host=args.host,
        artifact_format=cast(ArtifactFormat, args.format),
        catalog=args.catalog,
        schema=args.schema,
        bundle_name=args.bundle_name,
    )
    print(f"Bundle written to {out}")


if __name__ == "__main__":
    main()
