"""Exports a source workflow as a committed, deployable Databricks Asset Bundle.

Ties the whole pipeline together for the git -> DAB -> Databricks flow:
parse the workflow, generate its spec (offline rule-based here; the app's
LLM path produces the same PipelineSpec shape), render the chosen artifact
format, and write a self-contained bundle directory:

    <out>/
      databricks.yml           one target, generated by deploy/dab.py
      src/<name>.py            the rendered job script / notebook / SDP module
      src/<name>_utils.py      cleanse/macro helpers (only when the workflow uses them)

The output is meant to be committed to git and deployed with
`databricks bundle deploy` (auth via DATABRICKS_HOST / DATABRICKS_TOKEN env
vars — never stored in the bundle).

Usage:
    python -m deploy.export --workflow tests/fixtures/alteryx/sales_summary.yxmd \
        --format notebook --out bundles/sales_summary \
        --host https://<workspace>.cloud.databricks.com \
        --catalog workspace --schema default
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
from pathlib import Path
from typing import cast

from app.offline_convert import naive_spec_from_workflow
from convert.renderer import (
    render_databricks_notebook,
    render_pyspark,
    render_sdp,
    render_utility_module,
    utils_module_name,
)
from convert.spec import PipelineSpec, TargetRef
from deploy.dab import ArtifactFormat, single_target_bundle, write_databricks_yml
from deploy.models import dab_identifier
from ingest.alteryx.parser import parse_yxmd

_RENDERERS = {
    "job": render_pyspark,
    "notebook": render_databricks_notebook,
    "sdp": render_sdp,
}


def export_bundle_from_spec(
    spec: PipelineSpec,
    output_dir: str | Path,
    workspace_host: str,
    artifact_format: ArtifactFormat = "notebook",
    bundle_name: str | None = None,
) -> Path:
    """Render a validated spec and write a deployable bundle directory.

    The bundle name defaults to the pipeline name — bundle names are the
    deployment-state key, so two workflows sharing one name would replace
    each other's resources on deploy.
    """
    if bundle_name is None:
        bundle_name = re.sub(r"\W+", "_", spec.name).strip("_").lower()
    code = _RENDERERS[artifact_format](spec)

    # The artifact filename becomes a Databricks workspace path; keep it free
    # of spaces and other characters that break notebook/file paths.
    safe_stem = dab_identifier(spec.name)
    out = Path(output_dir)
    src_dir = out / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    # A re-export must fully replace the previous one: a renamed workflow or
    # a spec that no longer needs its utility module would otherwise leave
    # stale .py files in src/, silently uploaded on every later deploy.
    for stale in src_dir.glob("*.py"):
        stale.unlink()
    (src_dir / f"{safe_stem}.py").write_text(code, encoding="utf-8")

    # Macro/cleanse helpers render into a separate file, shared by whichever
    # format is chosen, and imported by the main artifact above.
    extra_paths: list[str] = []
    utility_code = render_utility_module(spec)
    if utility_code is not None:
        utility_filename = f"{utils_module_name(spec)}.py"
        (src_dir / utility_filename).write_text(utility_code, encoding="utf-8")
        extra_paths.append(f"./src/{utility_filename}")

    bundle = single_target_bundle(
        bundle_name=bundle_name,
        pipeline_name=spec.name,
        python_file=f"./src/{safe_stem}.py",
        workspace_host=workspace_host,
        catalog=spec.target.catalog,
        schema=spec.target.schema_,
        artifact_format=artifact_format,
        extra_artifact_paths=extra_paths,
    )
    write_databricks_yml(bundle, out / "databricks.yml")
    return out


def export_bundle(
    workflow_path: str | Path,
    output_dir: str | Path,
    workspace_host: str,
    artifact_format: ArtifactFormat = "notebook",
    catalog: str = "workspace",
    schema: str = "default",
    bundle_name: str | None = None,
) -> Path:
    """Parse, convert, render, and write a deployable bundle directory."""
    workflow = parse_yxmd(workflow_path)
    target = TargetRef(catalog=catalog, schema=schema, layer="bronze")
    spec = naive_spec_from_workflow(workflow, target)
    return export_bundle_from_spec(
        spec, output_dir, workspace_host, artifact_format=artifact_format, bundle_name=bundle_name
    )


def _cli_env(host: str, token: str | None) -> dict[str, str]:
    env = dict(os.environ)
    env["DATABRICKS_HOST"] = host
    if token:
        env["DATABRICKS_TOKEN"] = token
    return env


def validate_bundle(bundle_dir: str | Path, host: str, token: str | None = None) -> tuple[bool, str]:
    """Run `databricks bundle validate` — resolves and checks the bundle config
    without uploading files or touching Terraform. Cheap, fast pre-flight check.
    """
    result = subprocess.run(
        ["databricks", "bundle", "validate"],
        cwd=str(bundle_dir), env=_cli_env(host, token),
        capture_output=True, text=True, timeout=120,
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def deploy_bundle(bundle_dir: str | Path, host: str, token: str | None = None) -> tuple[bool, str]:
    """Validate, then run `databricks bundle deploy` for an exported bundle.

    Validating first catches config-shape errors (e.g. an invalid Terraform
    resource name) before the upload step, rather than after — `deploy`
    uploads bundle files first and only then runs Terraform, so a config
    error previously surfaced late with a partial upload already done.

    Auth comes from `token` (or the caller's environment when None). Returns
    (succeeded, combined CLI output incl. the deployed resource summary).
    """
    ok, validate_output = validate_bundle(bundle_dir, host, token)
    if not ok:
        return False, f"bundle validate failed:\n{validate_output}"

    env = _cli_env(host, token)
    deploy = subprocess.run(
        ["databricks", "bundle", "deploy"],
        cwd=str(bundle_dir), env=env, capture_output=True, text=True, timeout=600,
    )
    output = (deploy.stdout + deploy.stderr).strip()
    if deploy.returncode != 0:
        return False, output

    summary = subprocess.run(
        ["databricks", "bundle", "summary"],
        cwd=str(bundle_dir), env=env, capture_output=True, text=True, timeout=120,
    )
    return True, f"{output}\n\n{(summary.stdout + summary.stderr).strip()}"


def run_bundle_job(
    bundle_dir: str | Path,
    host: str,
    token: str | None = None,
    resource_key: str | None = None,
) -> tuple[bool, str]:
    """Run the bundle's job/pipeline and wait for it to finish.

    `resource_key` is the resource name inside databricks.yml (e.g.
    "<pipeline>_job"); when omitted it is read from the bundle file, since
    the CLI requires an explicit key when it cannot infer one.
    """
    if resource_key is None:
        import yaml

        doc = yaml.safe_load((Path(bundle_dir) / "databricks.yml").read_text(encoding="utf-8"))
        resources = doc.get("resources", {})
        keys = [k for kind in ("jobs", "pipelines") for k in resources.get(kind, {})]
        if not keys:
            return False, "No job or pipeline resource found in databricks.yml"
        resource_key = keys[0]

    result = subprocess.run(
        ["databricks", "bundle", "run", resource_key],
        cwd=str(bundle_dir), env=_cli_env(host, token),
        capture_output=True, text=True, timeout=1800,
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workflow", required=True, help="Path to the source .yxmd file")
    parser.add_argument("--out", required=True, help="Bundle output directory")
    parser.add_argument("--host", required=True, help="Databricks workspace URL")
    parser.add_argument("--format", default="notebook", choices=sorted(_RENDERERS))
    parser.add_argument("--catalog", default="workspace")
    parser.add_argument("--schema", default="default")
    parser.add_argument("--bundle-name", default=None, help="Defaults to the workflow name")
    args = parser.parse_args()

    out = export_bundle(
        workflow_path=args.workflow,
        output_dir=args.out,
        workspace_host=args.host,
        artifact_format=cast(ArtifactFormat, args.format),
        catalog=args.catalog,
        schema=args.schema,
        bundle_name=args.bundle_name,
    )
    print(f"Bundle written to {out}")


if __name__ == "__main__":
    main()
