"""Deterministically renders a validated PipelineSpec into PySpark source.

This is the only place that produces runnable code. The LLM never sees this
module's output before a human does — it only ever produces the YAML that
feeds `render_pyspark`.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from typing import Any

from convert.expr import alteryx_expr_to_spark
from convert.spec import (
    AggregateStep,
    CallFunctionStep,
    DistinctStep,
    FilterStep,
    JoinStep,
    PipelineSpec,
    ReadStep,
    RecordIdStep,
    SelectStep,
    SortStep,
    Step,
    UnionStep,
    WithColumnsStep,
    WriteStep,
)
from functions.registry import get_function

_HEADER = '''"""Generated by convert/renderer.py from the YAML spec for '{name}'.

DO NOT EDIT BY HAND — regenerate from the YAML spec instead. Human review
happens on the spec and on this generated file together in the PR, but future
changes should go through the spec so the two never drift apart.
"""

from pyspark.sql import functions as F  # noqa: N812
'''


def _var(step_id: str) -> str:
    return f"df_{step_id}"


def _render_read(step: ReadStep) -> str:
    return f'{_var(step.id)} = spark.table("{step.source_table}")  # alias: {step.alias}'


def _render_select(step: SelectStep) -> str:
    exprs = []
    for col in step.columns:
        if col.drop:
            continue
        if col.rename:
            exprs.append(f'F.col("{col.column}").alias("{col.rename}")')
        else:
            exprs.append(f'F.col("{col.column}")')
    cols = ", ".join(exprs)
    return f"{_var(step.id)} = {_var(step.input)}.select({cols})"


def _render_filter(step: FilterStep) -> str:
    condition = alteryx_expr_to_spark(step.condition)
    return f"{_var(step.id)} = {_var(step.input)}.filter(F.expr({condition!r}))"


def _render_with_columns(step: WithColumnsStep) -> str:
    lines = [f"{_var(step.id)} = {_var(step.input)}"]
    for col in step.columns:
        expr = alteryx_expr_to_spark(col.expression)
        lines.append(f'{_var(step.id)} = {_var(step.id)}.withColumn("{col.name}", F.expr({expr!r}))')
    return "\n".join(lines)


def _render_join(step: JoinStep) -> str:
    if step.use_function:
        fn = get_function(step.use_function)
        if fn is None:
            raise ValueError(f"Unknown function referenced by join step {step.id!r}: {step.use_function!r}")
        return (
            f"{_var(step.id)} = {step.use_function}("
            f"{_var(step.left)}, {_var(step.right)}, "
            f"left_keys={step.left_keys!r}, right_keys={step.right_keys!r}, how={step.how!r})"
        )
    on = " & ".join(
        f"({_var(step.left)}['{lk}'] == {_var(step.right)}['{rk}'])"
        for lk, rk in zip(step.left_keys, step.right_keys, strict=True)
    )
    return f"{_var(step.id)} = {_var(step.left)}.join({_var(step.right)}, on={on}, how={step.how!r})"


def _render_union(step: UnionStep) -> str:
    result = _var(step.inputs[0])
    for other in step.inputs[1:]:
        result = f"{result}.unionByName({_var(other)}, allowMissingColumns=True)"
    return f"{_var(step.id)} = {result}"


def _render_sort(step: SortStep) -> str:
    orderings = ", ".join(
        f'F.col("{c.column}").{"desc" if c.descending else "asc"}()' for c in step.columns
    )
    return f"{_var(step.id)} = {_var(step.input)}.orderBy({orderings})"


def _render_record_id(step: RecordIdStep) -> str:
    return (
        f'{_var(step.id)} = {_var(step.input)}.withColumn("{step.column}", '
        f"F.row_number().over(Window.orderBy(F.monotonically_increasing_id())))"
    )


def _render_distinct(step: DistinctStep) -> str:
    if step.columns:
        cols = ", ".join(f'"{c}"' for c in step.columns)
        return f"{_var(step.id)} = {_var(step.input)}.dropDuplicates([{cols}])"
    return f"{_var(step.id)} = {_var(step.input)}.dropDuplicates()"


_AGG_FUNCS = {"sum", "count", "avg", "min", "max"}


def _render_aggregate(step: AggregateStep) -> str:
    group_by = ", ".join(f'"{g}"' for g in step.group_by)
    aggs = []
    for agg in step.aggregations:
        if agg.func not in _AGG_FUNCS:
            raise ValueError(f"Unsupported aggregation function {agg.func!r} in step {step.id!r}")
        aggs.append(f'F.{agg.func}("{agg.column}").alias("{agg.alias}")')
    agg_str = ", ".join(aggs)
    return f"{_var(step.id)} = {_var(step.input)}.groupBy({group_by}).agg({agg_str})"


def _render_call_function(step: CallFunctionStep) -> str:
    fn = get_function(step.function)
    if fn is None:
        raise ValueError(f"Unknown function referenced by step {step.id!r}: {step.function!r}")
    kwargs = ", ".join(f"{k}={v!r}" for k, v in step.args.items())
    sep = ", " if kwargs else ""
    return f"{_var(step.id)} = {step.function}({_var(step.input)}{sep}{kwargs})"


_WRITE_MODES = {"overwrite", "append"}


def _render_write(step: WriteStep) -> str:
    if step.mode not in _WRITE_MODES:
        return (
            f"# TODO: mode={step.mode!r} is not yet rendered (needs a MERGE INTO statement).\n"
            f"{_var(step.id)} = {_var(step.input)}  # target_table={step.target_table}"
        )
    return f'{_var(step.input)}.write.mode({step.mode!r}).saveAsTable("{step.target_table}")'


_RENDERERS: dict[type, Callable[[Any], str]] = {
    ReadStep: _render_read,
    SelectStep: _render_select,
    FilterStep: _render_filter,
    WithColumnsStep: _render_with_columns,
    JoinStep: _render_join,
    UnionStep: _render_union,
    SortStep: _render_sort,
    DistinctStep: _render_distinct,
    RecordIdStep: _render_record_id,
    AggregateStep: _render_aggregate,
    CallFunctionStep: _render_call_function,
    WriteStep: _render_write,
}


def _render_step(step: Step) -> str:
    renderer = _RENDERERS.get(type(step))
    if renderer is None:
        raise ValueError(f"No renderer registered for step type {type(step).__name__}")
    return renderer(step)


def _function_imports(spec: PipelineSpec) -> list[str]:
    imports = []
    if any(isinstance(step, RecordIdStep) for step in spec.steps):
        imports.append("from pyspark.sql.window import Window")
    for name in spec.functions_used:
        fn = get_function(name)
        if fn is None:
            raise ValueError(f"Spec references unknown function {name!r}")
        module_path, attr = fn.import_path.rsplit(".", 1)
        imports.append(f"from {module_path} import {attr}")
    return sorted(set(imports))


def render_pyspark(spec: PipelineSpec) -> str:
    """Render a validated PySpark PipelineSpec into a runnable module source string."""
    if spec.language != "pyspark":
        raise ValueError(f"render_pyspark called with a {spec.language!r} spec")

    parts = [_HEADER.format(name=spec.name)]
    imports = _function_imports(spec)
    if imports:
        parts.append("\n".join(imports))
    parts.append("\n\ndef run(spark) -> None:  # noqa: ANN001")
    body_lines = [_render_step(step) for step in spec.steps]
    indented = "\n".join("    " + line.replace("\n", "\n    ") for line in body_lines)
    parts.append(indented)

    return "\n".join(parts) + "\n"


_NOTEBOOK_CELL_SEP = "\n\n# COMMAND ----------\n\n"


def render_databricks_notebook(spec: PipelineSpec) -> str:
    """Render a spec as Databricks notebook source, one cell per step.

    Notebooks have an ambient `spark` session, so unlike `render_pyspark`
    there is no `run(spark)` wrapper — steps run at top level, cell by cell,
    which is the shape engineers expect when stepping through a conversion
    interactively in a workspace.
    """
    if spec.language != "pyspark":
        raise ValueError(f"render_databricks_notebook called with a {spec.language!r} spec")

    imports = ["from pyspark.sql import functions as F  # noqa: N812", *_function_imports(spec)]
    cells = ["\n".join(imports)]
    cells.extend(_render_step(step) for step in spec.steps)

    header = (
        "# Databricks notebook source\n"
        f"# Generated by convert/renderer.py from the YAML spec for '{spec.name}'.\n"
        "# DO NOT EDIT BY HAND — regenerate from the YAML spec instead."
    )
    return header + _NOTEBOOK_CELL_SEP + _NOTEBOOK_CELL_SEP.join(cells) + "\n"


def _sdp_table_name(target_table: str) -> str:
    name = target_table.rsplit(".", 1)[-1]
    return re.sub(r"\W", "_", name)


def render_sdp(spec: PipelineSpec) -> str:
    """Render a spec as a Lakeflow/Spark Declarative Pipeline module.

    Uses the current `from pyspark import pipelines as dp` / `@dp.table` API
    (the successor to the legacy `import dlt` module). Each write step becomes
    one `@dp.table` function returning the dataframe that was going to be
    written; the pipeline runtime owns the actual write, so WriteStep's mode
    is not rendered here. The transform chain is replayed inside each table
    function — slight duplication across multi-output specs is accepted so
    every table function is self-contained.
    """
    if spec.language != "pyspark":
        raise ValueError(f"render_sdp called with a {spec.language!r} spec")

    writes = [s for s in spec.steps if isinstance(s, WriteStep)]
    if not writes:
        raise ValueError(f"Spec {spec.name!r} has no write steps; SDP needs at least one table")
    non_write_steps = [s for s in spec.steps if not isinstance(s, WriteStep)]

    parts = [_HEADER.format(name=spec.name), "from pyspark import pipelines as dp"]
    imports = _function_imports(spec)
    if imports:
        parts.append("\n".join(imports))

    for write in writes:
        table_name = _sdp_table_name(write.target_table)
        body_lines = [_render_step(step) for step in non_write_steps]
        body_lines.append(f"return {_var(write.input)}")
        indented = "\n".join("    " + line.replace("\n", "\n    ") for line in body_lines)
        parts.append(
            f'\n@dp.table(name="{table_name}", comment="Generated from spec {spec.name!r}")\n'
            f"def {table_name}():  # noqa: ANN201\n{indented}"
        )

    return "\n".join(parts) + "\n"
