"""Deterministically renders a validated PipelineSpec into PySpark source.

This is the only place that produces runnable code. The LLM never sees this
module's output before a human does — it only ever produces the YAML that
feeds `render_pyspark`.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from typing import Any

from convert.expr import alteryx_expr_to_spark, unknown_functions
from convert.spec import (
    AggregateStep,
    AppendFieldsStep,
    CallFunctionStep,
    CleanseStep,
    DistinctStep,
    FilterStep,
    FindReplaceStep,
    JoinStep,
    MacroCallStep,
    PipelineSpec,
    PythonScriptStep,
    ReadStep,
    RecordIdStep,
    SelectStep,
    SortStep,
    Step,
    UnionStep,
    WithColumnsStep,
    WriteStep,
)
from functions.registry import get_function

_HEADER = '''"""Generated by convert/renderer.py from the YAML spec for '{name}'.

DO NOT EDIT BY HAND — regenerate from the YAML spec instead. Human review
happens on the spec and on this generated file together in the PR, but future
changes should go through the spec so the two never drift apart.
"""

from pyspark.sql import functions as F  # noqa: N812
'''


def _var(step_id: str) -> str:
    return f"df_{step_id}"


def _render_read(step: ReadStep) -> str:
    return f'{_var(step.id)} = spark.table("{step.source_table}")  # alias: {step.alias}'


def _render_select(step: SelectStep) -> str:
    exprs = []
    for col in step.columns:
        if col.drop:
            continue
        if col.rename:
            exprs.append(f'F.col("{col.column}").alias("{col.rename}")')
        else:
            exprs.append(f'F.col("{col.column}")')
    cols = ", ".join(exprs)
    return f"{_var(step.id)} = {_var(step.input)}.select({cols})"


def _review_suffix(expr: str) -> str:
    unknown = unknown_functions(expr)
    if not unknown:
        return ""
    return f"  # REVIEW: verify {sorted(unknown)} translate correctly to Spark SQL"


def _render_filter(step: FilterStep) -> str:
    condition = alteryx_expr_to_spark(step.condition)
    return (
        f"{_var(step.id)} = {_var(step.input)}.filter(F.expr({condition!r}))"
        f"{_review_suffix(condition)}"
    )


def _render_with_columns(step: WithColumnsStep) -> str:
    lines = [f"{_var(step.id)} = {_var(step.input)}"]
    for col in step.columns:
        expr = alteryx_expr_to_spark(col.expression)
        lines.append(
            f'{_var(step.id)} = {_var(step.id)}.withColumn("{col.name}", F.expr({expr!r}))'
            f"{_review_suffix(expr)}"
        )
    return "\n".join(lines)


def _render_join(step: JoinStep) -> str:
    if step.use_function:
        fn = get_function(step.use_function)
        if fn is None:
            raise ValueError(f"Unknown function referenced by join step {step.id!r}: {step.use_function!r}")
        return (
            f"{_var(step.id)} = {step.use_function}("
            f"{_var(step.left)}, {_var(step.right)}, "
            f"left_keys={step.left_keys!r}, right_keys={step.right_keys!r}, how={step.how!r})"
        )
    on = " & ".join(
        f"({_var(step.left)}['{lk}'] == {_var(step.right)}['{rk}'])"
        for lk, rk in zip(step.left_keys, step.right_keys, strict=True)
    )
    return f"{_var(step.id)} = {_var(step.left)}.join({_var(step.right)}, on={on}, how={step.how!r})"


def _render_union(step: UnionStep) -> str:
    result = _var(step.inputs[0])
    for other in step.inputs[1:]:
        result = f"{result}.unionByName({_var(other)}, allowMissingColumns=True)"
    return f"{_var(step.id)} = {result}"


def _render_sort(step: SortStep) -> str:
    orderings = ", ".join(
        f'F.col("{c.column}").{"desc" if c.descending else "asc"}()' for c in step.columns
    )
    return f"{_var(step.id)} = {_var(step.input)}.orderBy({orderings})"


# Self-contained utility generated when a workflow used an Alteryx Data
# Cleansing macro — emitted into the artifact itself so deployed code has no
# dependency on this repo being installed on the cluster.
_CLEANSE_UTILITY = '''
def cleanse_columns(df, columns=None, trim=False, collapse_whitespace=False,
                    remove_all_whitespace=False, nulls_to_blank=False,
                    numeric_nulls_to_zero=False, case=None):
    """Utility generated from an Alteryx Data Cleansing macro."""
    from pyspark.sql import types as _T
    numeric_types = (_T.IntegerType, _T.LongType, _T.FloatType, _T.DoubleType,
                     _T.DecimalType, _T.ShortType, _T.ByteType)
    string_cols = {f.name for f in df.schema.fields if isinstance(f.dataType, _T.StringType)}
    numeric_cols = {f.name for f in df.schema.fields if isinstance(f.dataType, numeric_types)}
    targets = list(columns) if columns is not None else list(df.columns)

    out = df
    for name in targets:
        if name not in string_cols:
            continue
        col = F.col(name)
        if trim:
            col = F.trim(col)
        if collapse_whitespace:
            col = F.regexp_replace(col, r"\\s+", " ")
        if remove_all_whitespace:
            col = F.regexp_replace(col, r"\\s", "")
        if case == "upper":
            col = F.upper(col)
        elif case == "lower":
            col = F.lower(col)
        elif case == "title":
            col = F.initcap(col)
        if nulls_to_blank:
            col = F.coalesce(col, F.lit(""))
        out = out.withColumn(name, col)
    if numeric_nulls_to_zero:
        subset = [name for name in targets if name in numeric_cols]
        if subset:
            out = out.fillna(0, subset=subset)
    return out
'''


def _all_steps(spec: PipelineSpec) -> list[Step]:
    steps: list[Step] = list(spec.steps)
    for macro in spec.macros:
        steps.extend(macro.steps)
    return steps


def _uses_cleanse(spec: PipelineSpec) -> bool:
    return any(isinstance(step, CleanseStep) for step in _all_steps(spec))


_AYX_READ = re.compile(r"Alteryx\.read\(\s*[\"']#\d+[\"']\s*\)")
_AYX_WRITE = re.compile(r"Alteryx\.write\(\s*(.+?)\s*,\s*\d+\s*\)")
_AYX_CONST = re.compile(r"Alteryx\.getWorkflowConstant\(([^)]*)\)")


def adapt_python_code(code: str) -> str:
    """Rewrite Alteryx Python-tool code to run outside Designer.

    - ayx imports and installPackages calls are commented out;
    - Alteryx.read("#N") becomes the pandas input dataframe;
    - Alteryx.write(x, n) captures x as the output dataframe;
    - getWorkflowConstant becomes a TODO (no equivalent at runtime).
    """
    lines: list[str] = []
    for line in code.splitlines():
        stripped = line.strip()
        if (
            stripped.startswith(("from ayx", "import ayx"))
            or "Package.installPackages" in stripped
        ):
            lines.append("# [migrated] " + line)
            continue
        line = _AYX_READ.sub("_input_pdf", line)
        line = _AYX_WRITE.sub(r"_output_pdf = \1", line)
        line = _AYX_CONST.sub(r"None  # TODO: getWorkflowConstant(\1) has no runtime equivalent", line)
        lines.append(line)
    return "\n".join(lines)


def _render_python_script(step: PythonScriptStep) -> str:
    adapted = adapt_python_code(step.code)
    indented = "\n".join("    " + line if line.strip() else line for line in adapted.splitlines())
    fn = f"_python_script_{step.id}"
    return (
        f"def {fn}(df):  # noqa: ANN001, ANN201\n"
        f'    """Auto-adapted from the Alteryx Python tool — REVIEW REQUIRED.\n'
        f"    Runs on the driver via pandas; validate for large data volumes.\n"
        f'    """\n'
        f"    _input_pdf = df.toPandas()\n"
        f"    _output_pdf = _input_pdf\n"
        f"{indented}\n"
        f"    return spark.createDataFrame(_output_pdf)\n"
        f"{_var(step.id)} = {fn}({_var(step.input)})"
    )


def _render_find_replace(step: FindReplaceStep) -> str:
    mode_note = (
        "  # NOTE: Alteryx mode was FindAny (substring match); this renders an exact-match join"
        if step.find_mode == "FindAny"
        else ""
    )
    lookup = (
        f'{_var(step.right)}.select(F.col("{step.search_column}").alias("__fr_key"), '
        f'F.col("{step.replace_column}").alias("__fr_val")).dropDuplicates(["__fr_key"])'
    )
    return (
        f'{_var(step.id)} = {_var(step.left)}.join({lookup}, '
        f'on=F.col("{step.find_column}") == F.col("__fr_key"), how="left"){mode_note}\n'
        f'{_var(step.id)} = {_var(step.id)}.withColumn("{step.find_column}", '
        f'F.coalesce(F.col("__fr_val"), F.col("{step.find_column}"))).drop("__fr_key", "__fr_val")'
    )


def _render_append_fields(step: AppendFieldsStep) -> str:
    return f"{_var(step.id)} = {_var(step.target)}.crossJoin({_var(step.source)})"


def _render_macro_call(step: MacroCallStep) -> str:
    return f"{_var(step.id)} = {step.macro}({_var(step.input)})"


def _render_macro_utilities(spec: PipelineSpec) -> list[str]:
    """One generated function per converted .yxmc macro, shared by all formats."""
    parts = []
    for macro in spec.macros:
        body_lines = [_render_step(step) for step in macro.steps]
        body_lines.append(f"return {_var(macro.returns)}")
        indented = "\n".join("    " + line.replace("\n", "\n    ") for line in body_lines)
        parts.append(
            f"\ndef {macro.name}(df_macro_input):  # noqa: ANN001, ANN201\n"
            f'    """Utility generated from the Alteryx macro {macro.name!r}."""\n'
            f"{indented}"
        )
    return parts


def _render_cleanse(step: CleanseStep) -> str:
    kwargs = []
    if step.columns is not None:
        kwargs.append(f"columns={step.columns!r}")
    for flag in (
        "trim", "collapse_whitespace", "remove_all_whitespace",
        "nulls_to_blank", "numeric_nulls_to_zero",
    ):
        if getattr(step, flag):
            kwargs.append(f"{flag}=True")
    if step.case is not None:
        kwargs.append(f"case={step.case!r}")
    joined = (", " + ", ".join(kwargs)) if kwargs else ""
    return f"{_var(step.id)} = cleanse_columns({_var(step.input)}{joined})"


def _render_record_id(step: RecordIdStep) -> str:
    return (
        f'{_var(step.id)} = {_var(step.input)}.withColumn("{step.column}", '
        f"F.row_number().over(Window.orderBy(F.monotonically_increasing_id())))"
    )


def _render_distinct(step: DistinctStep) -> str:
    if step.columns:
        cols = ", ".join(f'"{c}"' for c in step.columns)
        return f"{_var(step.id)} = {_var(step.input)}.dropDuplicates([{cols}])"
    return f"{_var(step.id)} = {_var(step.input)}.dropDuplicates()"


_AGG_FUNCS = {
    "sum", "count", "avg", "min", "max",
    "first", "last", "stddev", "variance", "countDistinct",
}


def _render_aggregate(step: AggregateStep) -> str:
    group_by = ", ".join(f'"{g}"' for g in step.group_by)
    aggs = []
    for agg in step.aggregations:
        if agg.func not in _AGG_FUNCS:
            raise ValueError(f"Unsupported aggregation function {agg.func!r} in step {step.id!r}")
        aggs.append(f'F.{agg.func}("{agg.column}").alias("{agg.alias}")')
    agg_str = ", ".join(aggs)
    return f"{_var(step.id)} = {_var(step.input)}.groupBy({group_by}).agg({agg_str})"


def _render_call_function(step: CallFunctionStep) -> str:
    fn = get_function(step.function)
    if fn is None:
        raise ValueError(f"Unknown function referenced by step {step.id!r}: {step.function!r}")
    kwargs = ", ".join(f"{k}={v!r}" for k, v in step.args.items())
    sep = ", " if kwargs else ""
    return f"{_var(step.id)} = {step.function}({_var(step.input)}{sep}{kwargs})"


_WRITE_MODES = {"overwrite", "append"}

# Writer options that create the target as a column-mapping Delta table, so
# columns with spaces/brackets are accepted. Setting columnMapping.mode=name
# requires the reader/writer protocol bump, so both are pinned alongside it.
_COLUMN_MAPPING_OPTS = (
    '.option("delta.columnMapping.mode", "name")'
    '.option("delta.minReaderVersion", "2")'
    '.option("delta.minWriterVersion", "5")'
)


def _render_write(step: WriteStep, column_mapping: bool = False) -> str:
    if step.mode not in _WRITE_MODES:
        return (
            f"# TODO: mode={step.mode!r} is not yet rendered (needs a MERGE INTO statement).\n"
            f"{_var(step.id)} = {_var(step.input)}  # target_table={step.target_table}"
        )
    opts = _COLUMN_MAPPING_OPTS if column_mapping else ""
    return (
        f'{_var(step.input)}.write{opts}.mode({step.mode!r})'
        f'.saveAsTable("{step.target_table}")'
    )


_RENDERERS: dict[type, Callable[[Any], str]] = {
    ReadStep: _render_read,
    SelectStep: _render_select,
    FilterStep: _render_filter,
    WithColumnsStep: _render_with_columns,
    JoinStep: _render_join,
    UnionStep: _render_union,
    SortStep: _render_sort,
    DistinctStep: _render_distinct,
    RecordIdStep: _render_record_id,
    CleanseStep: _render_cleanse,
    MacroCallStep: _render_macro_call,
    PythonScriptStep: _render_python_script,
    FindReplaceStep: _render_find_replace,
    AppendFieldsStep: _render_append_fields,
    AggregateStep: _render_aggregate,
    CallFunctionStep: _render_call_function,
}


def _render_step(step: Step, *, column_mapping: bool = False) -> str:
    # WriteStep is routed specially so it can receive the spec-level
    # column-mapping flag (the dispatch dict is single-arg).
    if isinstance(step, WriteStep):
        return _render_write(step, column_mapping=column_mapping)
    renderer = _RENDERERS.get(type(step))
    if renderer is None:
        raise ValueError(f"No renderer registered for step type {type(step).__name__}")
    return renderer(step)


# Characters Delta rejects in a column name unless column mapping is enabled
# (spaces and structural punctuation), plus the brackets Alteryx cube-style
# field names carry. Any of these anywhere in a produced/consumed column name
# means the output table needs delta.columnMapping.mode = name.
_DELTA_UNSAFE_COL = re.compile(r"[ ,;{}()\[\]\t\n=]")


def _spec_column_names(spec: PipelineSpec) -> set[str]:
    """Every column name the spec reads or produces, across all steps."""
    names: set[str] = set()
    for step in _all_steps(spec):
        if isinstance(step, SelectStep):
            for col in step.columns:
                names.add(col.column)
                if col.rename:
                    names.add(col.rename)
        elif isinstance(step, WithColumnsStep):
            names.update(c.name for c in step.columns)
        elif isinstance(step, AggregateStep):
            names.update(step.group_by)
            for agg in step.aggregations:
                names.update((agg.column, agg.alias))
        elif isinstance(step, SortStep):
            names.update(c.column for c in step.columns)
        elif isinstance(step, DistinctStep):
            names.update(step.columns)
        elif isinstance(step, RecordIdStep):
            names.add(step.column)
        elif isinstance(step, CleanseStep) and step.columns:
            names.update(step.columns)
        elif isinstance(step, FindReplaceStep):
            names.update((step.find_column, step.search_column, step.replace_column))
        elif isinstance(step, JoinStep):
            names.update(step.left_keys)
            names.update(step.right_keys)
    return names


def _needs_column_mapping(spec: PipelineSpec) -> bool:
    """True when any column name would be illegal in a plain (unmapped) Delta table.

    Alteryx field names routinely contain spaces and brackets
    (`ProjectCube_Data[Redbox Customer]`, `Legal Entity`); Delta rejects
    those at write time unless the table has delta.columnMapping.mode = name.
    """
    return any(_DELTA_UNSAFE_COL.search(name) for name in _spec_column_names(spec))


def _function_imports(spec: PipelineSpec) -> list[str]:
    imports = []
    if any(isinstance(step, RecordIdStep) for step in _all_steps(spec)):
        imports.append("from pyspark.sql.window import Window")
    for name in spec.functions_used:
        fn = get_function(name)
        if fn is None:
            raise ValueError(f"Spec references unknown function {name!r}")
        module_path, attr = fn.import_path.rsplit(".", 1)
        imports.append(f"from {module_path} import {attr}")
    return sorted(set(imports))


def utils_module_name(spec: PipelineSpec) -> str:
    """Python-importable module name for spec's generated utility file.

    Distinct from deploy/export.py's artifact-filename sanitizer (which
    permits dashes, valid for Terraform/Databricks resource names but not
    for a Python module name) — this one only allows [A-Za-z0-9_].
    """
    stem = re.sub(r"[^A-Za-z0-9_]+", "_", spec.name).strip("_").lower()
    return f"{stem or 'workflow'}_utils"


def _utility_names(spec: PipelineSpec) -> list[str]:
    """Names importable from the generated utility module, if any exist."""
    names = ["cleanse_columns"] if _uses_cleanse(spec) else []
    names.extend(m.name for m in spec.macros)
    return names


def render_utility_module(spec: PipelineSpec) -> str | None:
    """Render cleanse/macro helpers as a standalone module, or None if unused.

    Kept separate from the main artifact so job/notebook/SDP all share one
    utility file per workflow instead of duplicating (and re-diffing) the
    same generated functions inline in every format.
    """
    if not _uses_cleanse(spec) and not spec.macros:
        return None
    parts = [
        f'"""Generated utility functions for {spec.name!r} '
        "(convert/renderer.py:render_utility_module).\n\n"
        "Imported by the main pipeline file — not meant to be run directly.\n"
        'DO NOT EDIT BY HAND — regenerate from the YAML spec instead.\n"""',
        "\nfrom pyspark.sql import functions as F  # noqa: N812",
    ]
    if _uses_cleanse(spec):
        parts.append(_CLEANSE_UTILITY)
    parts.extend(_render_macro_utilities(spec))
    return "\n".join(parts) + "\n"


def _utility_import_line(spec: PipelineSpec) -> str | None:
    names = _utility_names(spec)
    if not names:
        return None
    return f"from {utils_module_name(spec)} import {', '.join(names)}"


def render_pyspark(spec: PipelineSpec) -> str:
    """Render a validated PySpark PipelineSpec into a runnable module source string."""
    if spec.language != "pyspark":
        raise ValueError(f"render_pyspark called with a {spec.language!r} spec")

    parts = [_HEADER.format(name=spec.name)]
    imports = _function_imports(spec)
    if imports:
        parts.append("\n".join(imports))
    # A Databricks spark_python_task runs this as a plain script, so unlike
    # notebooks/pipeline library files, the deploy directory isn't guaranteed
    # on sys.path automatically — add it explicitly before importing the
    # sibling utility module.
    utility_import = _utility_import_line(spec)
    if utility_import:
        parts.append(
            "import os\nimport sys\n"
            "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\n"
            f"{utility_import}"
        )
    parts.append("\n\ndef run(spark) -> None:  # noqa: ANN001")
    col_map = _needs_column_mapping(spec)
    body_lines = [_render_step(step, column_mapping=col_map) for step in spec.steps]
    indented = "\n".join("    " + line.replace("\n", "\n    ") for line in body_lines)
    parts.append(indented)

    return "\n".join(parts) + "\n"


_NOTEBOOK_CELL_SEP = "\n\n# COMMAND ----------\n\n"


def render_databricks_notebook(spec: PipelineSpec) -> str:
    """Render a spec as Databricks notebook source, one cell per step.

    Notebooks have an ambient `spark` session, so unlike `render_pyspark`
    there is no `run(spark)` wrapper — steps run at top level, cell by cell,
    which is the shape engineers expect when stepping through a conversion
    interactively in a workspace.
    """
    if spec.language != "pyspark":
        raise ValueError(f"render_databricks_notebook called with a {spec.language!r} spec")

    imports = ["from pyspark.sql import functions as F  # noqa: N812", *_function_imports(spec)]
    utility_import = _utility_import_line(spec)
    if utility_import:
        # Databricks automatically adds a running notebook's own directory to
        # sys.path, so the sibling utility module (deployed alongside this
        # notebook) is importable directly with no path manipulation.
        imports.append(utility_import)
    cells = ["\n".join(imports)]
    col_map = _needs_column_mapping(spec)
    cells.extend(_render_step(step, column_mapping=col_map) for step in spec.steps)

    header = (
        "# Databricks notebook source\n"
        f"# Generated by convert/renderer.py from the YAML spec for '{spec.name}'.\n"
        "# DO NOT EDIT BY HAND — regenerate from the YAML spec instead."
    )
    return header + _NOTEBOOK_CELL_SEP + _NOTEBOOK_CELL_SEP.join(cells) + "\n"


def _sdp_table_name(target_table: str) -> str:
    name = target_table.rsplit(".", 1)[-1]
    return re.sub(r"\W", "_", name)


def _dp_table(
    name: str,
    comment: str,
    body_lines: list[str],
    table_properties: dict[str, str] | None = None,
) -> str:
    indented = "\n".join("    " + line.replace("\n", "\n    ") for line in body_lines)
    props = ""
    if table_properties:
        kv = ", ".join(f'"{k}": "{v}"' for k, v in table_properties.items())
        props = f", table_properties={{{kv}}}"
    return (
        f'\n@dp.table(name="{name}", comment="{comment}"{props})\n'
        f"def {name}():  # noqa: ANN201\n{indented}"
    )


def _step_refs(step: Step) -> list[str]:
    """Every other step id this step reads from, across all step types."""
    refs = [
        value
        for attr in ("input", "left", "right", "target", "source")
        if (value := getattr(step, attr, None)) is not None
    ]
    if isinstance(step, UnionStep):
        refs.extend(step.inputs)
    return refs


def _slice_dependencies(
    final_id: str, by_id: dict[str, Step], ordered: list[Step]
) -> tuple[list[Step], set[str]]:
    """Walk backward from `final_id` through `by_id`'s edges.

    Returns the subset of `ordered` it actually depends on (in original
    order) plus the set of ids it references outside `by_id` — upstream
    reads or silver-chain values that aren't part of this slice.
    """
    needed: set[str] = set()
    external: set[str] = set()
    stack = [final_id]
    while stack:
        current = stack.pop()
        if current in needed:
            continue
        step = by_id.get(current)
        if step is None:
            external.add(current)
            continue
        needed.add(current)
        stack.extend(_step_refs(step))
    return [s for s in ordered if s.id in needed], external


def render_sdp(spec: PipelineSpec) -> str:
    """Render a spec as a medallion-layered Lakeflow/Spark Declarative Pipeline.

    Uses the current `from pyspark import pipelines as dp` / `@dp.table` API
    (the successor to the legacy `import dlt` module), structured as:
    - bronze_<alias>: one raw landing table per source read;
    - silver_<name>: the cleaning/transform chain (selects, filters,
      formulas, joins...) reading from the bronze tables;
    - gold_<table>: one table per output, applying the aggregate steps (and
      anything after them) on silver — a pass-through materialization when
      the workflow has no aggregation.

    The pipeline runtime owns the writes, so WriteStep's mode is not
    rendered. Each gold table only computes the steps its own write
    depends on (see `_slice_dependencies`); a gold step that references a
    silver-chain id other than silver's own return value is approximated
    with silver's output and marked `# REVIEW` in the generated code, since
    silver only materializes its final row set, not every intermediate.
    """
    if spec.language != "pyspark":
        raise ValueError(f"render_sdp called with a {spec.language!r} spec")

    writes = [s for s in spec.steps if isinstance(s, WriteStep)]
    if not writes:
        raise ValueError(f"Spec {spec.name!r} has no write steps; SDP needs at least one table")

    reads = [s for s in spec.steps if isinstance(s, ReadStep)]
    middle: list[Step] = [s for s in spec.steps if not isinstance(s, ReadStep | WriteStep)]
    first_agg_index = next(
        (i for i, s in enumerate(middle) if isinstance(s, AggregateStep)), len(middle)
    )
    silver_steps = middle[:first_agg_index]
    gold_steps = middle[first_agg_index:]

    parts = [_HEADER.format(name=spec.name), "from pyspark import pipelines as dp"]
    # Special-character column names (Alteryx brackets/spaces) need Delta
    # column mapping on every table that stores them — bronze already
    # materializes the raw source columns, so all three layers get it.
    col_props = (
        {"delta.columnMapping.mode": "name"} if _needs_column_mapping(spec) else None
    )
    imports = _function_imports(spec)
    if imports:
        parts.append("\n".join(imports))
    utility_import = _utility_import_line(spec)
    if utility_import:
        # Lakeflow pipelines add each source file's own directory to
        # sys.path, so the sibling utility module (deployed as a second
        # pipeline library alongside this file) is importable directly.
        parts.append(utility_import)

    # Bronze: raw landing, one table per unique source. `@dp.table` names must
    # be unique in the pipeline, so two ReadSteps of the identical
    # source_table (a workflow can have more than one Input tool pointing at
    # the same table) are merged onto one bronze table instead of emitting
    # a duplicate definition, which Lakeflow would reject at deploy time.
    # Two *different* tables whose sanitized names collide get a numeric
    # suffix so they stay distinct.
    bronze_names: dict[str, str] = {}  # read.id -> emitted bronze table name
    bronze_by_source: dict[str, str] = {}  # source_table -> emitted bronze table name
    used_bronze_names: set[str] = set()
    for read in reads:
        if read.source_table in bronze_by_source:
            bronze_names[read.id] = bronze_by_source[read.source_table]
            continue
        base = f"bronze_{_sdp_table_name(read.alias)}"
        name, n = base, 2
        while name in used_bronze_names:
            name, n = f"{base}_{n}", n + 1
        used_bronze_names.add(name)
        bronze_by_source[read.source_table] = name
        bronze_names[read.id] = name
        parts.append(
            _dp_table(name, f"Raw landing of {read.source_table}",
                      [f'return spark.read.table("{read.source_table}")'],
                      table_properties=col_props)
        )

    # Silver: cleaned/conformed transforms over bronze.
    silver = f"silver_{_sdp_table_name(spec.name)}"
    silver_body = [
        f'{_var(read.id)} = spark.read.table("{bronze_names[read.id]}")' for read in reads
    ]
    silver_body.extend(_render_step(step) for step in silver_steps)
    silver_last = silver_steps[-1].id if silver_steps else (reads[-1].id if reads else "")
    silver_body.append(f"return {_var(silver_last)}")
    parts.append(
        _dp_table(silver, f"Transformed data for {spec.name}", silver_body,
                  table_properties=col_props)
    )

    # Gold: business-level output per write step. Each write's body includes
    # only the steps it actually depends on (walked backward through the
    # step graph from its final id), not the entire post-aggregation tail —
    # sharing one flattened list across every write duplicated unrelated
    # computation and, when two writes fell back to the same default id,
    # silently returned identical bodies for genuinely different outputs.
    # An external reference is resolved to its own bronze table when it's a
    # direct read; to the silver table when it matches silver's actual
    # return value; anything else is an intermediate silver-chain value that
    # silver doesn't expose as its own table, so it's approximated with
    # silver's output and flagged for human review.
    gold_by_id: dict[str, Step] = {s.id: s for s in gold_steps}
    gold_ids = set(gold_by_id)
    used_gold_names: dict[str, int] = {}
    reachable: set[str] = set()
    for write in writes:
        base = f"gold_{_sdp_table_name(write.target_table)}"
        seen = used_gold_names.get(base, 0)
        used_gold_names[base] = seen + 1
        gold = base if seen == 0 else f"{base}_{seen + 1}"
        comment = f"Business-level output {write.target_table}"
        if seen:
            comment += (
                " -- REVIEW: name collided with another write step after "
                "sanitization; confirm these are genuinely different outputs"
            )
        if gold_steps:
            final = write.input if write.input in gold_ids else gold_steps[-1].id
            if write.input not in gold_ids:
                comment += (
                    " -- REVIEW: write step's input did not match any "
                    "post-aggregation step id; fell back to the last computed "
                    "step, verify this is the intended output"
                )
            steps_needed, external_ids = _slice_dependencies(final, gold_by_id, gold_steps)
            reachable.update(s.id for s in steps_needed)
            body: list[str] = []
            for upstream_id in sorted(external_ids):
                if upstream_id in bronze_names:
                    body.append(
                        f'{_var(upstream_id)} = spark.read.table("{bronze_names[upstream_id]}")'
                    )
                elif upstream_id == silver_last:
                    body.append(f'{_var(upstream_id)} = spark.read.table("{silver}")')
                else:
                    body.append(
                        f'{_var(upstream_id)} = spark.read.table("{silver}")  '
                        f"# REVIEW: {upstream_id!r} is an intermediate value from the "
                        f"silver chain, not its final output — verify this substitution"
                    )
            body.extend(_render_step(step) for step in steps_needed)
            body.append(f"return {_var(final)}")
        else:
            body = [f'return spark.read.table("{silver}")']
        parts.append(_dp_table(gold, comment, body, table_properties=col_props))
        if write.mode in ("append", "merge"):
            # Alteryx ran this output incrementally. A materialized view is a
            # full refresh; converting to a streaming table (or apply_changes
            # for upsert) is only correct when the source is append-only, which
            # we can't assume here — so flag it rather than silently generate
            # streaming code against a batch source.
            kind = "append (incremental)" if write.mode == "append" else "update/upsert (CDC)"
            hint = (
                "if its source is append-only, make this a streaming table "
                "(spark.readStream.table(...))"
                if write.mode == "append"
                else "if its source is a change feed, use dp.create_streaming_table + "
                "dp.apply_changes for the upsert"
            )
            parts.append(
                f"\n# REVIEW: {write.target_table} used Alteryx {kind} output; this renders "
                f"as a full-refresh materialized view. {hint[0].upper()}{hint[1:]}."
            )

    orphaned = [s.id for s in gold_steps if s.id not in reachable]
    if orphaned:
        parts.append(
            f"\n# REVIEW: step(s) {orphaned} are computed after aggregation but never "
            "reach a write step in this spec — an output branch may be missing from "
            "the spec; verify against the source workflow."
        )

    return "\n".join(parts) + "\n"
