"""Deterministically renders a validated PipelineSpec into PySpark source.

This is the only place that produces runnable code. The LLM never sees this
module's output before a human does — it only ever produces the YAML that
feeds `render_pyspark`.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from typing import Any

from convert.expr import alteryx_expr_to_spark
from convert.spec import (
    AggregateStep,
    CallFunctionStep,
    CleanseStep,
    DistinctStep,
    FilterStep,
    JoinStep,
    PipelineSpec,
    ReadStep,
    RecordIdStep,
    SelectStep,
    SortStep,
    Step,
    UnionStep,
    WithColumnsStep,
    WriteStep,
)
from functions.registry import get_function

_HEADER = '''"""Generated by convert/renderer.py from the YAML spec for '{name}'.

DO NOT EDIT BY HAND — regenerate from the YAML spec instead. Human review
happens on the spec and on this generated file together in the PR, but future
changes should go through the spec so the two never drift apart.
"""

from pyspark.sql import functions as F  # noqa: N812
'''


def _var(step_id: str) -> str:
    return f"df_{step_id}"


def _render_read(step: ReadStep) -> str:
    return f'{_var(step.id)} = spark.table("{step.source_table}")  # alias: {step.alias}'


def _render_select(step: SelectStep) -> str:
    exprs = []
    for col in step.columns:
        if col.drop:
            continue
        if col.rename:
            exprs.append(f'F.col("{col.column}").alias("{col.rename}")')
        else:
            exprs.append(f'F.col("{col.column}")')
    cols = ", ".join(exprs)
    return f"{_var(step.id)} = {_var(step.input)}.select({cols})"


def _render_filter(step: FilterStep) -> str:
    condition = alteryx_expr_to_spark(step.condition)
    return f"{_var(step.id)} = {_var(step.input)}.filter(F.expr({condition!r}))"


def _render_with_columns(step: WithColumnsStep) -> str:
    lines = [f"{_var(step.id)} = {_var(step.input)}"]
    for col in step.columns:
        expr = alteryx_expr_to_spark(col.expression)
        lines.append(f'{_var(step.id)} = {_var(step.id)}.withColumn("{col.name}", F.expr({expr!r}))')
    return "\n".join(lines)


def _render_join(step: JoinStep) -> str:
    if step.use_function:
        fn = get_function(step.use_function)
        if fn is None:
            raise ValueError(f"Unknown function referenced by join step {step.id!r}: {step.use_function!r}")
        return (
            f"{_var(step.id)} = {step.use_function}("
            f"{_var(step.left)}, {_var(step.right)}, "
            f"left_keys={step.left_keys!r}, right_keys={step.right_keys!r}, how={step.how!r})"
        )
    on = " & ".join(
        f"({_var(step.left)}['{lk}'] == {_var(step.right)}['{rk}'])"
        for lk, rk in zip(step.left_keys, step.right_keys, strict=True)
    )
    return f"{_var(step.id)} = {_var(step.left)}.join({_var(step.right)}, on={on}, how={step.how!r})"


def _render_union(step: UnionStep) -> str:
    result = _var(step.inputs[0])
    for other in step.inputs[1:]:
        result = f"{result}.unionByName({_var(other)}, allowMissingColumns=True)"
    return f"{_var(step.id)} = {result}"


def _render_sort(step: SortStep) -> str:
    orderings = ", ".join(
        f'F.col("{c.column}").{"desc" if c.descending else "asc"}()' for c in step.columns
    )
    return f"{_var(step.id)} = {_var(step.input)}.orderBy({orderings})"


# Self-contained utility generated when a workflow used an Alteryx Data
# Cleansing macro — emitted into the artifact itself so deployed code has no
# dependency on this repo being installed on the cluster.
_CLEANSE_UTILITY = '''
def cleanse_columns(df, columns=None, trim=False, collapse_whitespace=False,
                    remove_all_whitespace=False, nulls_to_blank=False,
                    numeric_nulls_to_zero=False, case=None):
    """Utility generated from an Alteryx Data Cleansing macro."""
    from pyspark.sql import types as _T
    numeric_types = (_T.IntegerType, _T.LongType, _T.FloatType, _T.DoubleType,
                     _T.DecimalType, _T.ShortType, _T.ByteType)
    string_cols = {f.name for f in df.schema.fields if isinstance(f.dataType, _T.StringType)}
    numeric_cols = {f.name for f in df.schema.fields if isinstance(f.dataType, numeric_types)}
    targets = list(columns) if columns is not None else list(df.columns)

    out = df
    for name in targets:
        if name not in string_cols:
            continue
        col = F.col(name)
        if trim:
            col = F.trim(col)
        if collapse_whitespace:
            col = F.regexp_replace(col, r"\\s+", " ")
        if remove_all_whitespace:
            col = F.regexp_replace(col, r"\\s", "")
        if case == "upper":
            col = F.upper(col)
        elif case == "lower":
            col = F.lower(col)
        elif case == "title":
            col = F.initcap(col)
        if nulls_to_blank:
            col = F.coalesce(col, F.lit(""))
        out = out.withColumn(name, col)
    if numeric_nulls_to_zero:
        subset = [name for name in targets if name in numeric_cols]
        if subset:
            out = out.fillna(0, subset=subset)
    return out
'''


def _uses_cleanse(spec: PipelineSpec) -> bool:
    return any(isinstance(step, CleanseStep) for step in spec.steps)


def _render_cleanse(step: CleanseStep) -> str:
    kwargs = []
    if step.columns is not None:
        kwargs.append(f"columns={step.columns!r}")
    for flag in (
        "trim", "collapse_whitespace", "remove_all_whitespace",
        "nulls_to_blank", "numeric_nulls_to_zero",
    ):
        if getattr(step, flag):
            kwargs.append(f"{flag}=True")
    if step.case is not None:
        kwargs.append(f"case={step.case!r}")
    joined = (", " + ", ".join(kwargs)) if kwargs else ""
    return f"{_var(step.id)} = cleanse_columns({_var(step.input)}{joined})"


def _render_record_id(step: RecordIdStep) -> str:
    return (
        f'{_var(step.id)} = {_var(step.input)}.withColumn("{step.column}", '
        f"F.row_number().over(Window.orderBy(F.monotonically_increasing_id())))"
    )


def _render_distinct(step: DistinctStep) -> str:
    if step.columns:
        cols = ", ".join(f'"{c}"' for c in step.columns)
        return f"{_var(step.id)} = {_var(step.input)}.dropDuplicates([{cols}])"
    return f"{_var(step.id)} = {_var(step.input)}.dropDuplicates()"


_AGG_FUNCS = {"sum", "count", "avg", "min", "max"}


def _render_aggregate(step: AggregateStep) -> str:
    group_by = ", ".join(f'"{g}"' for g in step.group_by)
    aggs = []
    for agg in step.aggregations:
        if agg.func not in _AGG_FUNCS:
            raise ValueError(f"Unsupported aggregation function {agg.func!r} in step {step.id!r}")
        aggs.append(f'F.{agg.func}("{agg.column}").alias("{agg.alias}")')
    agg_str = ", ".join(aggs)
    return f"{_var(step.id)} = {_var(step.input)}.groupBy({group_by}).agg({agg_str})"


def _render_call_function(step: CallFunctionStep) -> str:
    fn = get_function(step.function)
    if fn is None:
        raise ValueError(f"Unknown function referenced by step {step.id!r}: {step.function!r}")
    kwargs = ", ".join(f"{k}={v!r}" for k, v in step.args.items())
    sep = ", " if kwargs else ""
    return f"{_var(step.id)} = {step.function}({_var(step.input)}{sep}{kwargs})"


_WRITE_MODES = {"overwrite", "append"}


def _render_write(step: WriteStep) -> str:
    if step.mode not in _WRITE_MODES:
        return (
            f"# TODO: mode={step.mode!r} is not yet rendered (needs a MERGE INTO statement).\n"
            f"{_var(step.id)} = {_var(step.input)}  # target_table={step.target_table}"
        )
    return f'{_var(step.input)}.write.mode({step.mode!r}).saveAsTable("{step.target_table}")'


_RENDERERS: dict[type, Callable[[Any], str]] = {
    ReadStep: _render_read,
    SelectStep: _render_select,
    FilterStep: _render_filter,
    WithColumnsStep: _render_with_columns,
    JoinStep: _render_join,
    UnionStep: _render_union,
    SortStep: _render_sort,
    DistinctStep: _render_distinct,
    RecordIdStep: _render_record_id,
    CleanseStep: _render_cleanse,
    AggregateStep: _render_aggregate,
    CallFunctionStep: _render_call_function,
    WriteStep: _render_write,
}


def _render_step(step: Step) -> str:
    renderer = _RENDERERS.get(type(step))
    if renderer is None:
        raise ValueError(f"No renderer registered for step type {type(step).__name__}")
    return renderer(step)


def _function_imports(spec: PipelineSpec) -> list[str]:
    imports = []
    if any(isinstance(step, RecordIdStep) for step in spec.steps):
        imports.append("from pyspark.sql.window import Window")
    for name in spec.functions_used:
        fn = get_function(name)
        if fn is None:
            raise ValueError(f"Spec references unknown function {name!r}")
        module_path, attr = fn.import_path.rsplit(".", 1)
        imports.append(f"from {module_path} import {attr}")
    return sorted(set(imports))


def render_pyspark(spec: PipelineSpec) -> str:
    """Render a validated PySpark PipelineSpec into a runnable module source string."""
    if spec.language != "pyspark":
        raise ValueError(f"render_pyspark called with a {spec.language!r} spec")

    parts = [_HEADER.format(name=spec.name)]
    imports = _function_imports(spec)
    if imports:
        parts.append("\n".join(imports))
    if _uses_cleanse(spec):
        parts.append(_CLEANSE_UTILITY)
    parts.append("\n\ndef run(spark) -> None:  # noqa: ANN001")
    body_lines = [_render_step(step) for step in spec.steps]
    indented = "\n".join("    " + line.replace("\n", "\n    ") for line in body_lines)
    parts.append(indented)

    return "\n".join(parts) + "\n"


_NOTEBOOK_CELL_SEP = "\n\n# COMMAND ----------\n\n"


def render_databricks_notebook(spec: PipelineSpec) -> str:
    """Render a spec as Databricks notebook source, one cell per step.

    Notebooks have an ambient `spark` session, so unlike `render_pyspark`
    there is no `run(spark)` wrapper — steps run at top level, cell by cell,
    which is the shape engineers expect when stepping through a conversion
    interactively in a workspace.
    """
    if spec.language != "pyspark":
        raise ValueError(f"render_databricks_notebook called with a {spec.language!r} spec")

    imports = ["from pyspark.sql import functions as F  # noqa: N812", *_function_imports(spec)]
    cells = ["\n".join(imports)]
    if _uses_cleanse(spec):
        cells.append(_CLEANSE_UTILITY.strip())
    cells.extend(_render_step(step) for step in spec.steps)

    header = (
        "# Databricks notebook source\n"
        f"# Generated by convert/renderer.py from the YAML spec for '{spec.name}'.\n"
        "# DO NOT EDIT BY HAND — regenerate from the YAML spec instead."
    )
    return header + _NOTEBOOK_CELL_SEP + _NOTEBOOK_CELL_SEP.join(cells) + "\n"


def _sdp_table_name(target_table: str) -> str:
    name = target_table.rsplit(".", 1)[-1]
    return re.sub(r"\W", "_", name)


def _dp_table(name: str, comment: str, body_lines: list[str]) -> str:
    indented = "\n".join("    " + line.replace("\n", "\n    ") for line in body_lines)
    return (
        f'\n@dp.table(name="{name}", comment="{comment}")\n'
        f"def {name}():  # noqa: ANN201\n{indented}"
    )


def render_sdp(spec: PipelineSpec) -> str:
    """Render a spec as a medallion-layered Lakeflow/Spark Declarative Pipeline.

    Uses the current `from pyspark import pipelines as dp` / `@dp.table` API
    (the successor to the legacy `import dlt` module), structured as:
    - bronze_<alias>: one raw landing table per source read;
    - silver_<name>: the cleaning/transform chain (selects, filters,
      formulas, joins...) reading from the bronze tables;
    - gold_<table>: one table per output, applying the aggregate steps (and
      anything after them) on silver — a pass-through materialization when
      the workflow has no aggregation.

    The pipeline runtime owns the writes, so WriteStep's mode is not
    rendered. Multi-output specs whose outputs branch mid-chain share the
    silver table; review the gold layer for those.
    """
    if spec.language != "pyspark":
        raise ValueError(f"render_sdp called with a {spec.language!r} spec")

    writes = [s for s in spec.steps if isinstance(s, WriteStep)]
    if not writes:
        raise ValueError(f"Spec {spec.name!r} has no write steps; SDP needs at least one table")

    reads = [s for s in spec.steps if isinstance(s, ReadStep)]
    middle = [s for s in spec.steps if not isinstance(s, ReadStep | WriteStep)]
    first_agg_index = next(
        (i for i, s in enumerate(middle) if isinstance(s, AggregateStep)), len(middle)
    )
    silver_steps = middle[:first_agg_index]
    gold_steps = middle[first_agg_index:]

    parts = [_HEADER.format(name=spec.name), "from pyspark import pipelines as dp"]
    imports = _function_imports(spec)
    if imports:
        parts.append("\n".join(imports))
    if _uses_cleanse(spec):
        parts.append(_CLEANSE_UTILITY)

    # Bronze: raw landing, one table per source.
    bronze_names: dict[str, str] = {}
    for read in reads:
        bronze = f"bronze_{_sdp_table_name(read.alias)}"
        bronze_names[read.id] = bronze
        parts.append(
            _dp_table(bronze, f"Raw landing of {read.source_table}",
                      [f'return spark.read.table("{read.source_table}")'])
        )

    # Silver: cleaned/conformed transforms over bronze.
    silver = f"silver_{_sdp_table_name(spec.name)}"
    silver_body = [
        f'{_var(read.id)} = spark.read.table("{bronze_names[read.id]}")' for read in reads
    ]
    silver_body.extend(_render_step(step) for step in silver_steps)
    silver_last = silver_steps[-1].id if silver_steps else (reads[-1].id if reads else "")
    silver_body.append(f"return {_var(silver_last)}")
    parts.append(_dp_table(silver, f"Transformed data for {spec.name}", silver_body))

    # Gold: business-level aggregates per output table.
    gold_ids = {s.id for s in gold_steps}
    for write in writes:
        gold = f"gold_{_sdp_table_name(write.target_table)}"
        body: list[str] = []
        referenced: set[str] = set()
        for step in gold_steps:
            for attr in ("input", "left", "right"):
                value = getattr(step, attr, None)
                if value is not None and value not in gold_ids:
                    referenced.add(value)
        if gold_steps:
            for upstream_id in sorted(referenced):
                body.append(f'{_var(upstream_id)} = spark.read.table("{silver}")')
            body.extend(_render_step(step) for step in gold_steps)
            final = write.input if write.input in gold_ids else gold_steps[-1].id
            body.append(f"return {_var(final)}")
        else:
            body.append(f'return spark.read.table("{silver}")')
        parts.append(_dp_table(gold, f"Business-level output {write.target_table}", body))

    return "\n".join(parts) + "\n"
