# Databricks notebook source
# Generated by convert/renderer.py from the YAML spec for 'sales_summary'.
# DO NOT EDIT BY HAND — regenerate from the YAML spec instead.

# COMMAND ----------

from pyspark.sql import functions as F  # noqa: N812
from functions.pyspark_lib.common import safe_join

# COMMAND ----------

df_1 = spark.table("legacy.sales.sales_raw")  # alias: sales_raw

# COMMAND ----------

df_2 = df_1.select(F.col("CustomerID"), F.col("Amount").alias("Amount"), F.col("Quantity"))

# COMMAND ----------

df_3 = df_2.filter(F.expr('`Amount` > 0'))

# COMMAND ----------

df_4 = df_3
df_4 = df_4.withColumn("LineTotal", F.expr('`Amount` * `Quantity`'))

# COMMAND ----------

df_5 = spark.table("legacy.sales.customers")  # alias: customers

# COMMAND ----------

df_6 = safe_join(df_4, df_5, left_keys=['CustomerID'], right_keys=['CustomerID'], how='inner')

# COMMAND ----------

df_7 = df_6.groupBy("CustomerID", "Region").agg(F.sum("LineTotal").alias("TotalSales"), F.count("LineTotal").alias("TransactionCount"))

# COMMAND ----------

df_7.write.mode('overwrite').saveAsTable("workspace.default.legacy_sales_sales_summary")
