# Databricks notebook source
# Generated by convert/renderer.py from the YAML spec for 'LS_Certifications_DEV_Load'.
# DO NOT EDIT BY HAND — regenerate from the YAML spec instead.

# COMMAND ----------

from pyspark.sql import functions as F  # noqa: N812
from pyspark.sql.window import Window

# COMMAND ----------

def cleanse_columns(df, columns=None, trim=False, collapse_whitespace=False,
                    remove_all_whitespace=False, nulls_to_blank=False,
                    numeric_nulls_to_zero=False, case=None):
    """Utility generated from an Alteryx Data Cleansing macro."""
    from pyspark.sql import types as _T
    numeric_types = (_T.IntegerType, _T.LongType, _T.FloatType, _T.DoubleType,
                     _T.DecimalType, _T.ShortType, _T.ByteType)
    string_cols = {f.name for f in df.schema.fields if isinstance(f.dataType, _T.StringType)}
    numeric_cols = {f.name for f in df.schema.fields if isinstance(f.dataType, numeric_types)}
    targets = list(columns) if columns is not None else list(df.columns)

    out = df
    for name in targets:
        if name not in string_cols:
            continue
        col = F.col(name)
        if trim:
            col = F.trim(col)
        if collapse_whitespace:
            col = F.regexp_replace(col, r"\s+", " ")
        if remove_all_whitespace:
            col = F.regexp_replace(col, r"\s", "")
        if case == "upper":
            col = F.upper(col)
        elif case == "lower":
            col = F.lower(col)
        elif case == "title":
            col = F.initcap(col)
        if nulls_to_blank:
            col = F.coalesce(col, F.lit(""))
        out = out.withColumn(name, col)
    if numeric_nulls_to_zero:
        subset = [name for name in targets if name in numeric_cols]
        if subset:
            out = out.fillna(0, subset=subset)
    return out

# COMMAND ----------

df_1 = spark.table("workspace.default.certifications")  # alias: certifications

# COMMAND ----------

df_19 = df_1
df_19 = df_19.withColumn("Display Status Updated", F.expr('left(`Display Status Updated`,19)'))

# COMMAND ----------

df_2 = df_19.select(F.col("Client ID").alias("Candidate_Registry_ID"), F.col("Last Name").alias("Candidate_Last_Name"), F.col("Middle Name").alias("Candidate_Middle_Name"), F.col("First Name").alias("Candidate_First_Name"), F.col("Certification Name").alias("Certification_Program_Name"), F.col("Status").alias("Certification_Program_Status"), F.col("Display Status Updated").alias("Last_Updated_Date"), F.col("Status Effective Date").alias("Status_Effective_Date"), F.col("Issued On").alias("Initial_Privileged_Date"), F.col("Expiration Date").alias("Status_Expiration_Date"), F.col("Credential Number").alias("Issued_Certification_ID"), F.col("Normalized Name").alias("Normalized_Name"), F.col("Company Name").alias("Company"), F.col("Email Address").alias("Candidate_Email"), F.col("Country"), F.col("Region"), F.col("Nokia ID").alias("Nokia_ID"), F.col("Program Family").alias("Program_Family"))

# COMMAND ----------

df_3 = cleanse_columns(df_2, columns=['Candidate_Registry_ID', 'Candidate_Last_Name', 'Candidate_Middle_Name', 'Candidate_First_Name', 'Certification_Program_Name', 'Certification_Program_Status', 'Last_Updated_Date', 'Status_Effective_Date', 'Initial_Privileged_Date', 'Status_Expiration_Date', 'Issued_Certification_ID', 'Normalized_Name', 'Company', 'Candidate_Email', 'Country', 'Region', 'Nokia_ID', 'Program_Family'], trim=True, nulls_to_blank=True)

# COMMAND ----------

df_14 = df_3.withColumn("Certification_ID", F.row_number().over(Window.orderBy(F.monotonically_increasing_id())))

# COMMAND ----------

df_10 = df_14
df_10 = df_10.withColumn("Quarter", F.expr("if(`Initial_Privileged_Date` IS NULL, NULL ,'Q' || string(Ceil(double(month(`Initial_Privileged_Date`))/3)))"))
df_10 = df_10.withColumn("Year", F.expr('substring(`Initial_Privileged_Date`, 1, 4)'))
df_10 = df_10.withColumn("Quarter_Year", F.expr("if(`Initial_Privileged_Date` IS NULL, NULL ,'Q' || string(Ceil(double(month(`Initial_Privileged_Date`))/3)) || '/' || Right(string(year(`Initial_Privileged_Date`)),2))"))
df_10 = df_10.withColumn("Customer_Type", F.expr('CASE WHEN NOT (`Nokia_ID` IS NULL OR `Nokia_ID` = \'\') THEN "Internal" ELSE "External" END'))
df_10 = df_10.withColumn("Load_Date", F.expr('current_timestamp()'))

# COMMAND ----------

df_10.write.mode('overwrite').saveAsTable("workspace.default.certifications_new")
