"""Generated by convert/renderer.py from the YAML spec for 'LS_Certifications_DEV_Load'.

DO NOT EDIT BY HAND — regenerate from the YAML spec instead. Human review
happens on the spec and on this generated file together in the PR, but future
changes should go through the spec so the two never drift apart.
"""

from pyspark.sql import functions as F  # noqa: N812

from pyspark import pipelines as dp
from pyspark.sql.window import Window
from ls_certifications_dev_load_utils import cleanse_columns

@dp.table(name="bronze_certifications", comment="Raw landing of migration_accelator.testing.certifications", table_properties={"delta.columnMapping.mode": "name"})
def bronze_certifications():  # noqa: ANN201
    return spark.read.table("migration_accelator.testing.certifications")

@dp.table(name="silver_LS_Certifications_DEV_Load", comment="Transformed data for LS_Certifications_DEV_Load", table_properties={"delta.columnMapping.mode": "name"})
def silver_LS_Certifications_DEV_Load():  # noqa: ANN201
    df_1 = spark.read.table("bronze_certifications")
    df_19 = df_1
    df_19 = df_19.withColumn("Display Status Updated", F.expr('left(`Display Status Updated`,19)'))
    df_2 = df_19.select(F.col("Client ID").cast("string").alias("Candidate_Registry_ID"), F.col("Last Name").cast("string").alias("Candidate_Last_Name"), F.col("Middle Name").cast("string").alias("Candidate_Middle_Name"), F.col("First Name").cast("string").alias("Candidate_First_Name"), F.col("Certification Name").cast("string").alias("Certification_Program_Name"), F.col("Status").cast("string").alias("Certification_Program_Status"), F.col("Display Status Updated").cast("timestamp").alias("Last_Updated_Date"), F.col("Status Effective Date").cast("date").alias("Status_Effective_Date"), F.col("Issued On").cast("date").alias("Initial_Privileged_Date"), F.col("Expiration Date").cast("date").alias("Status_Expiration_Date"), F.col("Credential Number").cast("string").alias("Issued_Certification_ID"), F.col("Normalized Name").cast("string").alias("Normalized_Name"), F.col("Company Name").cast("string").alias("Company"), F.col("Email Address").cast("string").alias("Candidate_Email"), F.col("Country").cast("string").alias("Country"), F.col("Region").cast("string").alias("Region"), F.col("Nokia ID").cast("string").alias("Nokia_ID"), F.col("Program Family").cast("string").alias("Program_Family"))
    df_3 = cleanse_columns(df_2, columns=['Candidate_Registry_ID', 'Candidate_Last_Name', 'Candidate_Middle_Name', 'Candidate_First_Name', 'Certification_Program_Name', 'Certification_Program_Status', 'Last_Updated_Date', 'Status_Effective_Date', 'Initial_Privileged_Date', 'Status_Expiration_Date', 'Issued_Certification_ID', 'Normalized_Name', 'Company', 'Candidate_Email', 'Country', 'Region', 'Nokia_ID', 'Program_Family'], trim=True, nulls_to_blank=True)
    df_14 = df_3.withColumn("Certification_ID", F.row_number().over(Window.orderBy(F.monotonically_increasing_id())))
    df_10 = df_14
    df_10 = df_10.withColumn("Quarter", F.expr("if(`Initial_Privileged_Date` IS NULL, NULL ,'Q' || string(Ceil(double(month(`Initial_Privileged_Date`))/3)))"))
    df_10 = df_10.withColumn("Year", F.expr('substring(`Initial_Privileged_Date`, 1, 4)'))
    df_10 = df_10.withColumn("Quarter_Year", F.expr("if(`Initial_Privileged_Date` IS NULL, NULL ,'Q' || string(Ceil(double(month(`Initial_Privileged_Date`))/3)) || '/' || Right(string(year(`Initial_Privileged_Date`)),2))"))
    df_10 = df_10.withColumn("Customer_Type", F.expr('CASE WHEN NOT (`Nokia_ID` IS NULL OR `Nokia_ID` = \'\') THEN "Internal" ELSE "External" END'))
    df_10 = df_10.withColumn("Load_Date", F.expr('current_timestamp()'))
    return df_10

@dp.table(name="gold_certifications_new", comment="Business-level output migration_accelator.testing.certifications_new", table_properties={"delta.columnMapping.mode": "name"})
def gold_certifications_new():  # noqa: ANN201
    return spark.read.table("silver_LS_Certifications_DEV_Load")
