# Databricks notebook source
# Generated by convert/renderer.py from the YAML spec for 'Alteryx Use Case Workflow'.
# DO NOT EDIT BY HAND — regenerate from the YAML spec instead.

# COMMAND ----------

from pyspark.sql import functions as F  # noqa: N812

# COMMAND ----------

df_src_28 = spark.table("workspace.default.todo_source_28")  # alias: todo_source_28

# COMMAND ----------

df_28 = df_src_28
df_28 = df_28.withColumn("SnapShotDate", F.expr('DateTimetoUTC(current_date())'))
df_28 = df_28.withColumn("ProjectCube_Data[Redbox Customer]", F.expr('LEFT(`ProjectCube_Data[Redbox Customer]`,30)'))
df_28 = df_28.withColumn("ProjectCube_Data[Account_ID]", F.expr('LEFT(`ProjectCube_Data[Account_ID]`,30)'))
df_28 = df_28.withColumn("ProjectCube_Data[Source_ID]", F.expr('LEFT(`ProjectCube_Data[Source_ID]`,15)'))
df_28 = df_28.withColumn("ProjectCube_Data[GIC]", F.expr('LEFT(`ProjectCube_Data[GIC]`,50)'))
df_28 = df_28.withColumn("ProjectCube_Data[Legal Entity]", F.expr('LEFT(`ProjectCube_Data[Legal Entity]`,30)'))

# COMMAND ----------

df_27 = df_28.select(F.col("ProjectCube_Data[Scenario]").alias("Scenario"), F.col("ProjectCube_Data[NokiaPeriod]").alias("NokiaPeriod"), F.col("ProjectCube_Data[Account_ID]").alias("Account_ID"), F.col("ProjectCube_Data[Source_ID]").alias("Source_ID"), F.col("ProjectCube_Data[Redbox Customer]").alias("Redbox Customer"), F.col("ProjectCube_Data[GIC]").alias("GIC"), F.col("ProjectCube_Data[TopWBS]").alias("TopWBS"), F.col("ProjectCube_Data[Legal Entity]").alias("Legal Entity"), F.col("[Base_Measure]").alias("Base_Measure"), F.col("SnapShotDate"))

# COMMAND ----------

df_30 = df_27
df_30 = df_30.withColumn("GIC", F.expr('LEFT(`GIC`,50)'))
df_30 = df_30.withColumn("Redbox Customer", F.expr('LEFT(`Redbox Customer`,30)'))
df_30 = df_30.withColumn("TopWBS", F.expr('LEFT(`TopWBS`,50)'))

# COMMAND ----------

df_30.write.mode('overwrite').saveAsTable("workspace.default.ionpmview_dbo_project_cube_le")
